### ISSUE TITLE
Your php version (7.3.33) does not satisfy that requirement

### ISSUE THREAD

**Issue by kmbremner** [drupal-tome/netlify-template#9]
The `mortenson/tome` docker image uses PHP 7.3, but to install composer packages in this repo, PHP 7.4 is requred.

**Steps to reproduce**
Visit https://gitpod.io/#https://github.com/drupal-tome/netlify-template - to open this repo as a new GitPod workspace.

Once the environment has loaded...

`composer install` gives:
```
  Problem 1
    - laminas/laminas-escaper is locked to version 2.10.0 and an update of this package was not requested.
    - laminas/laminas-escaper 2.10.0 requires php ^7.4 || ~8.0.0 || ~8.1.0 -> your php version (7.3.33) does not satisfy that requirement.
  Problem 2
    - psr/container is locked to version 1.1.2 and an update of this package was not requested.
    - psr/container 1.1.2 requires php >=7.4.0 -> your php version (7.3.33) does not satisfy that requirement.
  Problem 3
    - psr/container 1.1.2 requires php >=7.4.0 -> your php version (7.3.33) does not satisfy that requirement.
    - symfony/dependency-injection v4.4.42 requires psr/container ^1.0 -> satisfiable by psr/container[1.1.2].
    - symfony/dependency-injection is locked to version v4.4.42 and an update of this package was not requested.
```

`composer require drupal-tome/bookish` also gives:
```
  Problem 1
    - psr/container 1.1.2 requires php >=7.4.0 -> your php version (7.3.33) does not satisfy that requirement.
    - drupal/core 9.3.15 requires symfony/dependency-injection ^4.4 -> satisfiable by symfony/dependency-injection[v4.4.42].
    - symfony/dependency-injection v4.4.42 requires psr/container ^1.0 -> satisfiable by psr/container[1.1.2].
    - drupal/core is locked to version 9.3.15 and an update of this package was not requested.
```

**Comment by mortenson** [comment]
Thanks for the report @kmbremner ! I'm pretty loose with PHP versions in the Docker image https://github.com/drupal-tome/tome-docker so I'll just try upgrading for now. If I automated docker pushes I would probably want to have tags per version as well.

**Comment by mortenson** [comment]
@kmbremner I've just pushed a new version of the `mortenson/tome:latest` tag which uses PHP 7.4. Let me know if you run into any issues!

**Comment by mortenson** [comment]
@kmbremner I also noticed that you were using GitPod on this repo instead of your own - I'm not sure if that was just to demonstrate the issue but if you are trying to build a site with this template, make sure to start by clicking the "Deploy to Netlify" button in the README!

**Comment by mortenson** [comment]
Also see https://github.com/gitpod-io/gitpod/issues/7149 which is causing the image to be cached. May have to wait a few days.
